// src/game/unitschema.cpp
// GENERATED by the m2u scratch script genschema_unit.py from the disassembly
// of HD FUN_004c8680 (do not edit by hand; regenerate).
//
// FUN_004c8680 is a static initializer (36,766 bytes of operator new + ctor
// calls) that builds the .unit property schema and stores its root, the
// Struct "Unit", in HD 0x929a44. SUnitRegistry::LoadUnitFiles 0x5d1050 and
// GetPUnit 0x5d0e70 create an instance of it (0x664960) per .unit file and
// load it from the [Unit] section. 371 nodes. Node order, names, ranges and
// defaults are HD's. "T" is the shared "(Tooltip...)" description. Every
// Expr node evaluates against unitvariables.ini (HD 0x929a28).
// OWNER: agent U.

#include <float.h>
#include "unitprops.h"

namespace pz {

static const char* const T = "(Tooltip...)";

// PANZERS 0x4c8680
SUPProp* BuildUnitSchema()
{
    return
        new SUPPropStruct("Unit", T, true, {
            new SUPPropStruct("Common", T, false, {
                new SUPPropString("ModelName", T, ""),
                new SUPPropString("LowPolyModelName", T, ""),
                new SUPPropString("WreckModelName", T, ""),
                new SUPPropString("SpriteModelName", T, ""),
                new SUPPropEnum("UnitType", "Milyen t\xed""pus\xfa"" az egys\xe9""g(m\xfb""k\xf6""d\xe9""s szempontj\xe1""b\xf3""l)", 0, {{"Tank", 0}, {"SF_Antitank", 1}, {"SF_Artillery", 2}, {"Truck", 3}, {"SF_Airdefense", 4}, {"Boat", 5}, {"Ammo", 6}, {"Repair", 7}, {"Artillery", 8}, {"Antitank", 9}, {"Recon", 10}, {"Airdefense", 11}, {"Train", 12}, {"Building", 13}, {"Crew", 14}, {"Flamethrower", 15}, {"Medic", 16}, {"MG", 17}, {"Mortar", 18}, {"Parachute", 19}, {"Rifle", 20}, {"Rocket", 21}, {"SMG", 22}, {"Sniper", 23}, {"AT", 24}, {"Waster - TankMine", 25}, {"Building - Multi - Productive", 26}, {"TacBomber", 27}, {"HeavyBomber", 28}, {"ReconPlane", 29}}),
                new SUPPropInt("MarketBuyFirst", "Legkor\xe1""bban ebben a k\xfc""ldet\xe9""sben v\xe1""s\xe1""rolhat\xf3"" (0 = soha, -1 = mindig)", -1, 20, -1),
                new SUPPropInt("MarketBuyLast", "Legk\xe9""s\xf5""bb ebben a k\xfc""ldet\xe9""sben v\xe1""s\xe1""rolhat\xf3"" (0 = soha, -1 = mindig)", -1, 20, -1),
                new SUPPropEnum("MarketMultiWhenBuyable", "A h\xe1""bor\xfa"" melyik szakasz\xe1""ban v\xe1""s\xe1""rolhat\xf3"" multiban", 0, {{"Mindig", 0}, {"Elej\xe9""n", 1}, {"V\xe9""g\xe9""n", 2}, {"Soha", 3}}),
                new SUPPropExpr("Price", "Egyseg ara", 0.0f, FLT_MAX, "0"),
                new SUPPropInt("MarketPicture", "Marketben melyik kep jelenjen meg", -1, 2147483647, -1),
                new SUPPropInt("HeroPicture", "Jatekban melyik kep jelenjen meg(ha -1 akkor ez az egyseg nem hos)", -1, 10, -1),
                new SUPPropBool("Repairer", "Javito egyseg", false),
                new SUPPropBool("Supporter", "Utanpotlas szallito egyseg", false),
                new SUPPropExpr("Cargo", "Mennyi repair vagy ammo toltest kepes vegre hajtani", 0.0f, FLT_MAX, "0"),
                new SUPPropEnum("UnloadDirection", "Melyik oldalt sz\xe1""llnak ki az emberek", -1, {{"Left", -1}, {"Rear", 0}, {"Right", 1}, {"Random", 2}}),
                new SUPPropMulti("ClassType", T, 0, {
                    new SUPPropStruct("Single Unit", T, true, {
                        new SUPPropBool("BuiltInDriver", "Sof\xf5""r van-e benne beheggesztve", false),
                        new SUPPropString("BuiltInDriverUnitName", "A be\xe9""p\xed""tett sof\xf5""r ha l\xe1""that\xf3"", akkor add meg a Unit nev\xe9""t, ha nem l\xe1""that\xf3"", hagyd \xfc""resen!", ""),
                        new SUPPropInt("StorageCapacity", "H\xe1""ny csapat tud besz\xe1""llni", 0, 10, 1),
                        new SUPPropEnum("StorageType", "Milyen t\xed""pus\xfa"" egys\xe9""gek sz\xe1""llhatnak bele", 0, {{"Squad", 0}, {"J\xe1""rm\xfb""", 1}, {"Mindegyik", 2}}),
                        new SUPPropArray("Child Units", T, 0, 10, 0,
                            new SUPPropStruct("ChildUnit", T, false, {
                                new SUPPropString("UnitName", T, ""),
                                new SUPPropString("MeshName", T, "")})),
                        new SUPPropBool("OnlyCrew", "Csak crew vezetheti", false),
                        new SUPPropEnum("DemolishType", "Milyen object-eket tud kid\xf6""nteni (Light = nem tud; Medium = kisebb f\xe1""kat, faker\xed""t\xe9""st; Heavy = nagy f\xe1""kat, k\xf5""ker\xed""t\xe9""st).", 0, {{"Light", 0}, {"Medium", 1}, {"Heavy", 2}})}),
                    new SUPPropStruct("Squad Unit", T, true, {
                        new SUPPropInt("MaxNumberOfUnits", T, 0, 100, 0),
                        new SUPPropString("SquadMemberName", T, ""),
                        new SUPPropInt("Formations", T, 0, 255, 0)}),
                    new SUPPropStruct("Squad Member Unit", T, true, {}),
                    new SUPPropStruct("Projectile Unit", T, true, {
                        new SUPPropArray("Ground_Incidence_Effects", T, 0, 100, 0,
                            new SUPPropStruct("Effect", T, false, {
                                new SUPPropString("Effect", T, ""),
                                new SUPPropString("MeshName", T, "")})),
                        new SUPPropArray("Water_Incidence_Effects", T, 0, 100, 0,
                            new SUPPropStruct("Effect", T, false, {
                                new SUPPropString("Effect", T, ""),
                                new SUPPropString("MeshName", T, "")})),
                        new SUPPropArray("Unit_Incidence_Effects", T, 0, 100, 0,
                            new SUPPropStruct("Effect", T, false, {
                                new SUPPropString("Effect", T, ""),
                                new SUPPropString("MeshName", T, "")})),
                        new SUPPropArray("Building_Wood_Incidence_Effects", T, 0, 100, 0,
                            new SUPPropStruct("Effect", T, false, {
                                new SUPPropString("Effect", T, ""),
                                new SUPPropString("MeshName", T, "")})),
                        new SUPPropArray("Building_Stone_Incidence_Effects", T, 0, 100, 0,
                            new SUPPropStruct("Effect", T, false, {
                                new SUPPropString("Effect", T, ""),
                                new SUPPropString("MeshName", T, "")}))}),
                    new SUPPropStruct("Child Unit", T, true, {}),
                    new SUPPropStruct("Panzers Squad Unit", T, true, {
                        new SUPPropInt("MaxNumberOfUnits", "Maximum h\xe1""ny emberes a csapat", 0, 100, 0),
                        new SUPPropString("SquadMemberName", "Milyen unit-okbol \xe1""ll a squad", ""),
                        new SUPPropInt("Formations", T, 0, 255, 0)}),
                    new SUPPropStruct("Panzers Squad Member Unit", T, true, {}),
                    new SUPPropStruct("Waster Unit", "Akna, tuz es egyebek", true, {
                        new SUPPropFloat("LifeTime", "Ha nem 0 akkor errol a szamrol visszaszamol mielott megsemmisul(pl magneses akna)", 0.0f, FLT_MAX, 1.0f),
                        new SUPPropBool("Sensor", "Csak akkor lep mukodesbe ha ellenfellel utkozott(pl tank akna)", false),
                        new SUPPropBool("RemoteControl", "Csak akkor lep mukodesbe ha valaki mukodesbe hozza(pl explosives)", false)}),
                    new SUPPropStruct("Flying Unit", "Repulogepek", true, {
                        new SUPPropEnum("PlaneType", "Repulo tipusa", 0, {{"Glider", 0}, {"Recon plane", 1}, {"Tactical bomber", 2}, {"Heavy bomber", 3}})}),
                    new SUPPropStruct("Building Unit", "Specialis epuletek tartoznak ebbe a kategoriaba", true, {
                        new SUPPropBool("BuildingDowngrading", "(Tooltip!)", true),
                        new SUPPropEnum("BuildingType", "Epulet tipusa", 0, {{"House", 0}, {"Basement", 1}, {"Tower", 2}, {"Capturable", 3}, {"Locked", 4}, {"FlyingFox Station", 5}, {"Hangar", 6}}),
                        new SUPPropEnum("BuildingMaterial", "Epulet anyaga", 0, {{"Brick", 0}, {"Wood", 1}, {"Concrete", 2}}),
                        new SUPPropFloat("CaptureRange", "Elfoglalhat\xf3"" \xe9""p\xfc""letet max. ennyi m\xe9""terr\xf5""l lehet elfoglalni", 0.0f, 1e+02f, 24.0f)}),
                    new SUPPropStruct("Train Unit", T, true, {
                        new SUPPropBool("BuiltInDriver", "Sof\xf5""r van-e benne beheggesztve", false),
                        new SUPPropString("BuiltInDriverUnitName", "A be\xe9""p\xed""tett sof\xf5""r ha l\xe1""that\xf3"", akkor add meg a Unit nev\xe9""t, ha nem l\xe1""that\xf3"", hagyd \xfc""resen!", ""),
                        new SUPPropInt("StorageCapacity", "H\xe1""ny csapat tud besz\xe1""llni", 0, 10, 1),
                        new SUPPropEnum("StorageType", "Milyen t\xed""pus\xfa"" egys\xe9""gek sz\xe1""llhatnak bele", 0, {{"Squad", 0}, {"J\xe1""rm\xfb""", 1}, {"Mindegyik", 2}})}),
                    new SUPPropStruct("Artillery Unit", T, true, {
                        new SUPPropInt("StorageCapacity", "H\xe1""ny csapat tud besz\xe1""llni", 0, 10, 1),
                        new SUPPropEnum("StorageType", "Milyen t\xed""pus\xfa"" egys\xe9""gek sz\xe1""llhatnak bele", 0, {{"Squad", 0}, {"J\xe1""rm\xfb""", 1}, {"Mindegyik", 2}}),
                        new SUPPropEnum("DemolishType", "Milyen object-eket tud kid\xf6""nteni (Light = nem tud; Medium = kisebb f\xe1""kat, faker\xed""t\xe9""st; Heavy = nagy f\xe1""kat, k\xf5""ker\xed""t\xe9""st).", 0, {{"Light", 0}, {"Medium", 1}, {"Heavy", 2}})}),
                    new SUPPropStruct("Boat Unit", T, true, {
                        new SUPPropBool("BuiltInDriver", "Sof\xf5""r van-e benne beheggesztve", false),
                        new SUPPropString("BuiltInDriverUnitName", "A be\xe9""p\xed""tett sof\xf5""r ha l\xe1""that\xf3"", akkor add meg a Unit nev\xe9""t, ha nem l\xe1""that\xf3"", hagyd \xfc""resen!", ""),
                        new SUPPropInt("StorageCapacity", "H\xe1""ny csapat tud besz\xe1""llni", 0, 10, 1),
                        new SUPPropEnum("StorageType", "Milyen t\xed""pus\xfa"" egys\xe9""gek sz\xe1""llhatnak bele", 0, {{"Squad", 0}, {"J\xe1""rm\xfb""", 1}, {"Mindegyik", 2}})}),
                    new SUPPropStruct("FlyingFox Truck Unit", "", true, {
                        new SUPPropInt("StorageCapacity", "H\xe1""ny csapat tud besz\xe1""llni", 0, 10, 1),
                        new SUPPropEnum("StorageType", "Milyen t\xed""pus\xfa"" egys\xe9""gek sz\xe1""llhatnak bele", 0, {{"Squad", 0}, {"Vehicle", 1}, {"Squad & Vehicle", 2}})})}),
                new SUPPropArray("Static_Effects", T, 0, 100, 0,
                    new SUPPropStruct("Effect", T, false, {
                        new SUPPropString("Effect", T, ""),
                        new SUPPropString("MeshName", T, "")})),
                new SUPPropArray("Pilot_Light_Effects", T, 0, 100, 0,
                    new SUPPropStruct("Effect", T, false, {
                        new SUPPropString("Effect", T, ""),
                        new SUPPropString("MeshName", T, "")})),
                new SUPPropArray("Die_Effects", T, 0, 100, 0,
                    new SUPPropStruct("Effect", T, false, {
                        new SUPPropString("Effect", T, ""),
                        new SUPPropString("MeshName", T, "")})),
                new SUPPropArray("Died_by_Fire_Effects", T, 0, 100, 0,
                    new SUPPropStruct("Effect", T, false, {
                        new SUPPropString("Effect", T, ""),
                        new SUPPropString("MeshName", T, "")})),
                new SUPPropArray("Destroy_Effects", T, 0, 100, 0,
                    new SUPPropStruct("Effect", T, false, {
                        new SUPPropString("Effect", T, ""),
                        new SUPPropString("MeshName", T, "")})),
                new SUPPropArray("Night_Effects", "The head/tail light effects that can be turned on/off during night missions.", 0, 100, 0,
                    new SUPPropStruct("Effect", "", false, {
                        new SUPPropString("Effect", "Name (and path) of the effect file.", ""),
                        new SUPPropString("MeshName", "Name of the mesh the effect is attached to.", "")})),
                new SUPPropFloat("UnitSize", "A letilt\xe1""s \xe1""tm\xe9""r\xf5""je (m)", 0.0f, FLT_MAX, 1.0f),
                new SUPPropBool("Selectable", "Ki lehet-e jel\xf6""lni az egys\xe9""get", true),
                new SUPPropBool("Detector", "L\xe1""tja-e a l\xe1""thatatlan egys\xe9""geket (pl. akna)", false),
                new SUPPropBool("Invulnerable", "Sebezhetetlen", false),
                new SUPPropBool("Invisible", "L\xe1""thatatlan", false),
                new SUPPropBool("AlwaysVisible", "Mindig l\xe1""that\xf3"" (fog-of-war -ban is)", false),
                new SUPPropBool("CanMoveOnOnlyWalkerFlag", "Az only_walker flagen festett ter\xfc""leteken is tud mozogni.", false),
                new SUPPropBool("CanMoveOn_BM_EDGE_Flag", "A p\xe1""lya sz\xe9""l\xe9""re ki is tud menni miut\xe1""n bej\xf6""tt, ha nem CONTROL_HUMAN ir\xe1""ny\xed""totta.", false),
                new SUPPropExpr("Sight", "Sight", 0.0f, 95.0f, "30"),
                new SUPPropExpr("HP", "HitPoints", 0.0f, FLT_MAX, "0"),
                new SUPPropEnum("ArmourType", T, 0, {{"Infantry", 0}, {"Unarmoured vehicle", 1}, {"Armoured vehicle", 2}, {"Building", 3}}),
                new SUPPropExpr("Thermostat", "Max Hofok: felrobban a tank", 2e+01f, 1e+02f, "50"),
                new SUPPropFloat("FrontArmor", T, 0.0f, FLT_MAX, 0.0f),
                new SUPPropFloat("LeftSideArmor", T, 0.0f, FLT_MAX, 0.0f),
                new SUPPropFloat("RightSideArmor", T, 0.0f, FLT_MAX, 0.0f),
                new SUPPropFloat("BackArmor", T, 0.0f, FLT_MAX, 0.0f),
                new SUPPropFloat("TopArmor", T, 0.0f, FLT_MAX, 0.0f),
                new SUPPropBool("AttackGround", "Tud-e zarotuzet(foldet loni)", false),
                new SUPPropStruct("Slots", "Felszerelesek gyalogosoknak (ez az egyseg tipus milyen fajtat hasznalhat)", false, {
                    new SUPPropBool("Grenade", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Molotov coctail", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Mine detector", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Ground tank mine", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Magnetic mine", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Explosives", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Spade", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Binoculars", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Boat", "Lehet-e ilyen felszerelese", false),
                    new SUPPropBool("Mine", "Lehet-e ilyen felszerelese", false)}),
                new SUPPropInt("MainGunner", "Melyik gunner tud parancsot adni a drivernek is", -1, 10, 0),
                new SUPPropFloat("FireHeight", "Milyen magasan egjen a tuz, ha eltalaljak a unit-ot egy molotov koktellal.", 0.0f, FLT_MAX, 0.0f)}),
            new SUPPropArray("Gunners", T, 0, 10, 0,
                new SUPPropStruct("Gunner", T, false, {
                    new SUPPropEnum("GunnerType", T, 0, {{"Against ground units", 0}, {"Air defense", 1}}),
                    new SUPPropFloat("GunnerHeight", "Fegyvercs\xf5"" forg\xe1""spont / r\xf6""gz\xed""t\xe9""si pont magass\xe1""ga [m\xe9""terben]", 0.0f, FLT_MAX, 0.0f),
                    new SUPPropEnum("WeaponType", T, 0, {{"Bullet", 0}, {"AT(armor-piercing shell )", 1}, {"HE(explosion)", 2}, {"Fire", 3}}),
                    new SUPPropFloat("WeaponFireStartArcAngle", "Milyen iranyba lo alapban(pl bt 7-es gepfegyvere ellentese iranyba lo mint a parent gunnere)", 0.0f, 359.0f, 0.0f),
                    new SUPPropFloat("WeaponFireArcAngle", "Milyen szeles ivben lo, anelkul, hogy mozditana ", 0.0f, 9e+01f, 0.0f),
                    new SUPPropInt("ParentGunner", "Melyik gunner-el mozog egyutt", -1, 10, -1),
                    new SUPPropMulti("HandToHand / Ranged", "K\xf6""zelharci egys\xe9""g vagy t\xe1""volra l\xf6""v\xf5""", 0, {
                        new SUPPropStruct("HandToHand", T, true, {
                            new SUPPropFloat("MaxRange", T, 0.0f, FLT_MAX, 1.8f)}),
                        new SUPPropStruct("Ranged", T, true, {
                            new SUPPropExpr("MinRange", T, 0.0f, FLT_MAX, "0"),
                            new SUPPropExpr("MaxRange", T, 0.0f, FLT_MAX, "6"),
                            new SUPPropExpr("Ammo", T, 0.0f, FLT_MAX, "0"),
                            new SUPPropBool("DirectDamage", "Tenylegesen lo-e projectilet vagy a lovedek azonnal becsapodik", true),
                            new SUPPropArray("Projectiles", "L\xf6""ved\xe9""k unitok", 0, 10, 0,
                                new SUPPropStruct("Projectile", T, false, {
                                    new SUPPropString("Name", "L\xf6""ved\xe9""k unit neve", "")})),
                            new SUPPropExpr("KickSize", "Cs\xf5"" visszal\xf6""k\xf5""d\xe9""s m\xe9""rete", 0.0f, FLT_MAX, "0"),
                            new SUPPropExpr("KickTime", "Cs\xf5"" visszacs\xfb""sz\xe1""s ideje", 0.0f, FLT_MAX, "1"),
                            new SUPPropExpr("ShotAngle", "L\xf6""ved\xe9""k kil\xf6""v\xe9""si magass\xe1""gi sz\xf6""g (\xed""vben l\xf6""v\xf5"" gunnern\xe9""l)", 0.0f, 9e+01f, "0"),
                            new SUPPropExpr("ShotSpread", "Mekkora sugar\xfa"" k\xf6""rben sz\xf3""r (\xed""vben l\xf6""v\xf5"" gunnern\xe9""l)", 0.0f, FLT_MAX, "0")})}),
                    new SUPPropMulti("Fixed / Rotatable", "A parent-hez k\xe9""pest forgathat\xf3""-e", 1, {
                        new SUPPropStruct("Fixed", T, true, {}),
                        new SUPPropStruct("Rotatable", T, true, {
                            new SUPPropFloat("TurretSpeed", "Forg\xe1""si sebess\xe9""g (fok/s)", 0.0f, FLT_MAX, 3.6e+02f),
                            new SUPPropFloat("MaxLeftAngle", "WeaponFireStartArcAngle kepest bal iranyba max mennyit fordulhat a torony. 180 nal teljesen korbe tud fordulni", 0.0f, 1.8e+02f, 1.8e+02f),
                            new SUPPropFloat("MaxRightAngle", "WeaponFireStartArcAngle kepest jobb iranyba max mennyit fordulhat a torony. 180 nal teljesen korbe tud fordulni", 0.0f, 1.8e+02f, 1.8e+02f)})}),
                    new SUPPropExpr("Damage", T, 0.0f, FLT_MAX, "0"),
                    new SUPPropExpr("DamageRadius", T, 0.0f, FLT_MAX, "0"),
                    new SUPPropMulti("Direct / Radius Damage", "Ter\xfc""letre sebez-e", 1, {
                        new SUPPropStruct("Direct Damage", T, true, {
                            new SUPPropExpr("Damage", T, 0.0f, FLT_MAX, "0")}),
                        new SUPPropStruct("Radius Damage", T, true, {
                            new SUPPropExpr("Damage", T, 0.0f, FLT_MAX, "0"),
                            new SUPPropExpr("DamageRadius", T, 0.0f, FLT_MAX, "0")})}),
                    new SUPPropExpr("ReloadTime", "A l\xf6""v\xe9""s befejez\xe9""s\xe9""t\xf5""l a k\xf6""vetkez\xf5"" l\xf6""v\xe9""s elkezd\xe9""s\xe9""ig eltelt id\xf5"" (s)", 0.0f, FLT_MAX, "1"),
                    new SUPPropFloat("ReshotTime", "Sorozatl\xf6""v\xe9""sn\xe9""l az egyes l\xf6""v\xe9""sek k\xf6""z\xf6""tti id\xf5"" (s)", 0.0f, FLT_MAX, 0.1f),
                    new SUPPropFloat("ShotDelay", "A l\xf6""v\xe9""s anim\xe1""ci\xf3"" elkezd\xe9""s\xe9""t\xf6""l a t\xe9""nyleges l\xf6""v\xe9""sig eltelt id\xf5"" (s)", 0.0f, FLT_MAX, 0.0f),
                    new SUPPropBool("AutoShot", "M\xe1""sodlagos fegyver l\xf5""-e automat\xe1""n (vagy csak parancsra)", true),
                    new SUPPropInt("BurstShot", "Sorozatl\xf6""v\xe9""s (l\xf6""v\xe9""sek sz\xe1""ma)", 0, 2147483647, 0),
                    new SUPPropFloat("BodyKick", "Visszarug\xe1""s (mekkor\xe1""t l\xf6""k a testen)", 0.0f, FLT_MAX, 0.0f),
                    new SUPPropArray("Shot_Effects", T, 0, 100, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")})),
                    new SUPPropArray("Ground_Incidence_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")})),
                    new SUPPropArray("Water_Incidence_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")})),
                    new SUPPropArray("Unit_Incidence_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")})),
                    new SUPPropArray("Building_Wood_Incidence_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")})),
                    new SUPPropArray("Building_Stone_Incidence_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")}))})),
            new SUPPropArray("Drivers", T, 0, 10, 0,
                new SUPPropStruct("Driver", T, false, {
                    new SUPPropMulti("DriverType", T, 0, {
                        new SUPPropStruct("TurnInPlace", "Helyben fordul\xf3""", true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "10"),
                            new SUPPropExpr("SpinSpeed", "Fordul\xe1""si sebess\xe9""g [\xb0""/s]", 0.0f, FLT_MAX, "60"),
                            new SUPPropFloat("MaxFuel", T, 0.0f, FLT_MAX, 0.0f),
                            new SUPPropFloat("Consume", T, 0.0f, FLT_MAX, 0.0f)}),
                        new SUPPropStruct("TurnInAngle", "\xcd""vben fordul\xf3""", true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "10"),
                            new SUPPropFloat("WheelTurnAngle", "[\xb0""] - ker\xe9""k-kifordul\xe1""si sz\xf6""g (Ne \xed""rd \xe1""t!)", 0.0f, 9e+01f, 6e+01f),
                            new SUPPropFloat("Wheelbase", "[m] - tengelyek t\xe1""vols\xe1""ga", 0.0f, FLT_MAX, 4.0f),
                            new SUPPropFloat("MaxFuel", T, 0.0f, FLT_MAX, 0.0f),
                            new SUPPropFloat("Consume", T, 0.0f, FLT_MAX, 0.0f)}),
                        new SUPPropStruct("Helicopter", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "10"),
                            new SUPPropExpr("SpinSpeed", "Fordul\xe1""si sebess\xe9""g [\xb0""/s]", 0.0f, FLT_MAX, "60")}),
                        new SUPPropStruct("Flying", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "10"),
                            new SUPPropFloat("WheelTurnAngle", "[\xb0""] - ker\xe9""k-kifordul\xe1""si sz\xf6""g", 0.0f, 9e+01f, 6e+01f),
                            new SUPPropFloat("Wheelbase", "[m] - tengelyek t\xe1""vols\xe1""ga", 0.0f, FLT_MAX, 4.0f),
                            new SUPPropFloat("MaxFuel", T, 0.0f, FLT_MAX, 0.0f),
                            new SUPPropFloat("Consume", T, 0.0f, FLT_MAX, 0.0f),
                            new SUPPropFloat("Altitude", "Zero altitude / Kezdo magassag", 0.0f, FLT_MAX, 6.0f),
                            new SUPPropBool("Ground Tracking", "Zero altitude / Kezdo magassag", true),
                            new SUPPropFloat("MaxTilting", "Maximum ennyire doljon be a repulo", 0.0f, FLT_MAX, 0.8f)}),
                        new SUPPropStruct("Zeppelin", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "10"),
                            new SUPPropExpr("SpinSpeed", "Fordul\xe1""si sebess\xe9""g [\xb0""/s]", 0.0f, FLT_MAX, "60")}),
                        new SUPPropStruct("Walker", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "10"),
                            new SUPPropExpr("SpinSpeed", "Fordul\xe1""si sebess\xe9""g [\xb0""/s]", 0.0f, FLT_MAX, "60")}),
                        new SUPPropStruct("Projectile", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h] - Csak raketameghajtasnal van hasznalva", 0.0f, FLT_MAX, "10"),
                            new SUPPropBool("RocketPropulsion", "Raketameghajtas", false),
                            new SUPPropFloat("MaxFuel", "Raketa uzemanyag", 0.0f, FLT_MAX, 4e+01f)}),
                        new SUPPropStruct("Squad", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "0"),
                            new SUPPropExpr("SpinSpeed", "Fordul\xe1""si sebess\xe9""g [\xb0""/s]", 0.0f, FLT_MAX, "60000")}),
                        new SUPPropStruct("SquadMember", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "0"),
                            new SUPPropExpr("SpinSpeed", "Fordul\xe1""si sebess\xe9""g [\xb0""/s]", 0.0f, FLT_MAX, "0")}),
                        new SUPPropStruct("ChildUnit", T, true, {
                            new SUPPropFloat("DeltaX", T, -FLT_MAX, FLT_MAX, 0.0f),
                            new SUPPropFloat("DeltaZ", T, -FLT_MAX, FLT_MAX, 0.0f)}),
                        new SUPPropStruct("PanzersSquad", T, true, {}),
                        new SUPPropStruct("PanzerSquadMember", T, true, {}),
                        new SUPPropStruct("ParachuteSquadMember", T, true, {}),
                        new SUPPropStruct("Train", T, true, {
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "10")})}),
                    new SUPPropArray("Departure_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")})),
                    new SUPPropArray("Move_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")})),
                    new SUPPropArray("Move_In_Water_Effects", T, 0, 10, 0,
                        new SUPPropStruct("Effect", T, false, {
                            new SUPPropString("Effect", T, ""),
                            new SUPPropString("MeshName", T, "")}))})),
            new SUPPropMulti("Animation", T, 0, {
                new SUPPropStruct("None", T, true, {}),
                new SUPPropStruct("Vehicle", T, true, {
                    new SUPPropFloat("SpringStrength", T, 0.0f, FLT_MAX, 5.0f),
                    new SUPPropFloat("SpringDecay", T, 0.0f, FLT_MAX, 0.1f),
                    new SUPPropFloat("SpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("MaxSpringAngle", T, 0.0f, FLT_MAX, 1e+01f),
                    new SUPPropFloat("RodSpringStrength", T, 0.0f, FLT_MAX, 2.5f),
                    new SUPPropFloat("RodSpringDecay", T, 0.0f, FLT_MAX, 0.05f),
                    new SUPPropFloat("RodSpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("TrackWidth", "Nyomt\xe1""v", 0.0f, FLT_MAX, 1.0f),
                    new SUPPropMulti("CaterpillarBelt", T, 0, {
                        new SUPPropStruct("Disabled", T, true, {}),
                        new SUPPropStruct("Enabled", T, true, {
                            new SUPPropString("Trail", T, ""),
                            new SUPPropFloat("TrailWidth", T, 0.0f, FLT_MAX, 0.25f),
                            new SUPPropFloat("TrailTextureMovement", T, -FLT_MAX, FLT_MAX, 0.0f)})}),
                    new SUPPropArray("WheelTypes", T, 0, 10, 0,
                        new SUPPropStruct("Wheel", T, true, {
                            new SUPPropEnum("Type", T, 0, {{"Texture rotated", 0}, {"Mesh rotated", 1}, {"Mesh rotated & steered", 2}}),
                            new SUPPropFloat("Radius", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("U", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("V", T, -FLT_MAX, FLT_MAX, 1.0f)}))}),
                new SUPPropStruct("Walker", T, true, {
                    new SUPPropString("ShadowTexture", T, ""),
                    new SUPPropArray("States", T, 0, 10, 0,
                        new SUPPropStruct("State", T, false, {
                            new SUPPropString("StateText", T, "normal"),
                            new SUPPropExpr("MoveSpeed", "[km/h]", 0.0f, FLT_MAX, "0"),
                            new SUPPropExpr("SpinSpeed", "Fordul\xe1""si sebess\xe9""g [\xb0""/s]", 0.0f, FLT_MAX, "0")}))}),
                new SUPPropStruct("Projectile", T, true, {}),
                new SUPPropStruct("Squad", T, true, {}),
                new SUPPropStruct("Building", T, true, {}),
                new SUPPropStruct("Waster", T, true, {}),
                new SUPPropStruct("Flying", T, true, {
                    new SUPPropFloat("SpringStrength", T, 0.0f, FLT_MAX, 5.0f),
                    new SUPPropFloat("SpringDecay", T, 0.0f, FLT_MAX, 0.1f),
                    new SUPPropFloat("SpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("MaxSpringAngle", T, 0.0f, FLT_MAX, 1e+01f),
                    new SUPPropFloat("RodSpringStrength", T, 0.0f, FLT_MAX, 2.5f),
                    new SUPPropFloat("RodSpringDecay", T, 0.0f, FLT_MAX, 0.05f),
                    new SUPPropFloat("RodSpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("TrackWidth", "Nyomt\xe1""v", 0.0f, FLT_MAX, 1.0f),
                    new SUPPropMulti("CaterpillarBelt", T, 0, {
                        new SUPPropStruct("Disabled", T, true, {}),
                        new SUPPropStruct("Enabled", T, true, {
                            new SUPPropString("Trail", T, ""),
                            new SUPPropFloat("TrailWidth", T, 0.0f, FLT_MAX, 0.25f),
                            new SUPPropFloat("TrailTextureMovement", T, -FLT_MAX, FLT_MAX, 0.0f)})}),
                    new SUPPropArray("WheelTypes", T, 0, 10, 0,
                        new SUPPropStruct("Wheel", T, true, {
                            new SUPPropEnum("Type", T, 0, {{"Texture rotated", 0}, {"Mesh rotated", 1}, {"Mesh rotated & steered", 2}}),
                            new SUPPropFloat("Radius", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("U", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("V", T, -FLT_MAX, FLT_MAX, 1.0f)}))}),
                new SUPPropStruct("Train", T, true, {
                    new SUPPropFloat("SpringStrength", T, 0.0f, FLT_MAX, 5.0f),
                    new SUPPropFloat("SpringDecay", T, 0.0f, FLT_MAX, 0.1f),
                    new SUPPropFloat("SpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("MaxSpringAngle", T, 0.0f, FLT_MAX, 1e+01f),
                    new SUPPropFloat("RodSpringStrength", T, 0.0f, FLT_MAX, 2.5f),
                    new SUPPropFloat("RodSpringDecay", T, 0.0f, FLT_MAX, 0.05f),
                    new SUPPropFloat("RodSpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("TrackWidth", "Nyomt\xe1""v", 0.0f, FLT_MAX, 1.0f),
                    new SUPPropMulti("CaterpillarBelt", T, 0, {
                        new SUPPropStruct("Disabled", T, true, {}),
                        new SUPPropStruct("Enabled", T, true, {
                            new SUPPropString("Trail", T, ""),
                            new SUPPropFloat("TrailWidth", T, 0.0f, FLT_MAX, 0.25f),
                            new SUPPropFloat("TrailTextureMovement", T, -FLT_MAX, FLT_MAX, 0.0f)})}),
                    new SUPPropArray("WheelTypes", T, 0, 10, 0,
                        new SUPPropStruct("Wheel", T, true, {
                            new SUPPropEnum("Type", T, 0, {{"Texture rotated", 0}, {"Mesh rotated", 1}, {"Mesh rotated & steered", 2}}),
                            new SUPPropFloat("Radius", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("U", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("V", T, -FLT_MAX, FLT_MAX, 1.0f)}))}),
                new SUPPropStruct("Boat", T, true, {
                    new SUPPropFloat("SpringStrength", T, 0.0f, FLT_MAX, 5.0f),
                    new SUPPropFloat("SpringDecay", T, 0.0f, FLT_MAX, 0.1f),
                    new SUPPropFloat("SpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("MaxSpringAngle", T, 0.0f, FLT_MAX, 1e+01f),
                    new SUPPropFloat("RodSpringStrength", T, 0.0f, FLT_MAX, 2.5f),
                    new SUPPropFloat("RodSpringDecay", T, 0.0f, FLT_MAX, 0.05f),
                    new SUPPropFloat("RodSpringScale", T, 0.0f, FLT_MAX, 0.5f),
                    new SUPPropFloat("TrackWidth", "Nyomt\xe1""v", 0.0f, FLT_MAX, 1.0f),
                    new SUPPropMulti("CaterpillarBelt", T, 0, {
                        new SUPPropStruct("Disabled", T, true, {}),
                        new SUPPropStruct("Enabled", T, true, {
                            new SUPPropString("Trail", T, ""),
                            new SUPPropFloat("TrailWidth", T, 0.0f, FLT_MAX, 0.25f),
                            new SUPPropFloat("TrailTextureMovement", T, -FLT_MAX, FLT_MAX, 0.0f)})}),
                    new SUPPropArray("WheelTypes", T, 0, 10, 0,
                        new SUPPropStruct("Wheel", T, true, {
                            new SUPPropEnum("Type", T, 0, {{"Texture rotated", 0}, {"Mesh rotated", 1}, {"Mesh rotated & steered", 2}}),
                            new SUPPropFloat("Radius", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("U", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SUPPropFloat("V", T, -FLT_MAX, FLT_MAX, 1.0f)}))}),
                new SUPPropStruct("FLyingFox", "FIXME: Under Construction.", true, {})})});
}

} // namespace pz
