// src/3dengine/pz/effectschema.cpp
// GENERATED by the m1c scratch script genschema.py from the disassembly of
// the HD SPixie constructor 0x6941e0 (do not edit by hand; regenerate).
//
// The SPixie ctor builds two SPProperty schema trees with nested
// operator new + ctor calls (35 KB of code, 487 nodes):
//   PProperty_Effects (HD 0x92f108): Array "Effects" of Struct "Data", the
//     [ExtendedFx2] layout of every .fx file. Its EffectType multi has one
//     struct per effect class (00_PARTICLES .. 11_SANDSTORM); the index is
//     the case number of SPixie::InitEffectPrototype 0x69d6a0.
//   PProperty_EFX (HD 0x92f100): Struct "EFX", an older single-effect
//     layout (kept for fidelity; nothing in the menu path reads it).
// Node order, names, ranges and defaults are HD's. "T" is the shared
// "(Tooltip!)" description string at 0x7fefd8.
// OWNER: agent C.

#include <float.h>
#include "propertystruct.h"
#include "effect.h"

namespace pz {

static const char* const T = "(Tooltip!)";

// Part of SPixie::SPixie 0x6941e0 (0x69432a..0x69a40a).
SPProperty* BuildEffectsSchema()
{
    return
        new SPPropertyArray("Effects", "", 0, 16, 0,
            new SPPropertyStruct("Data", "", true, {
                new SPPropertyBool("Enabled", "", true),
                new SPPropertyString("Name", "", "Effect"),
                new SPPropertyInt("PriorityLayer", "", 0, 2, 1),
                new SPPropertyBool("ForceUpdate", "When set to TRUE, the effect will always be updated.", false),
                new SPPropertyMulti("EffectType", "", 0, {
                    new SPPropertyStruct("00_PARTICLES", T, true, {
                        new SPPropertyMulti("Draw", T, 0, {
                            new SPPropertyStruct("Particles", T, true, {
                                new SPPropertyEnum("ParticleType", T, 0, {{"Normal", 0}, {"Billboard", 1}, {"Cloud", 2}, {"Trail", 3}}),
                                new SPPropertyFloat("TrailLength", "A trail particletype eseten a trail hosszusaga. Alapertelmezeskent 2, tehat ketszer olyan hosszu, mint szeles", 0.1f, 1e+02f, 2.0f),
                                new SPPropertyEnum("TrailOrientation", "", 0, {{"Center", 0}, {"FromPivot", 1}}),
                                new SPPropertyEnum("BlendType", T, 0, {{"Alpha", 0}, {"Add", 1}}),
                                new SPPropertyBool("ElevDependent", "Camera elevation dependent transparency", true),
                                new SPPropertyBool("ZBuffer On", T, true),
                                new SPPropertyColor("Color", "A particle-k szine.", 0xFFFFFF),
                                new SPPropertyBool("Random rotate", "A keletkezesnel random elforgatja a particle-kat. Egyelore csak normal es cloud particle type eseten mukodik.", false),
                                new SPPropertyMulti("Texture Anim in", T, 1, {
                                    new SPPropertyStruct("More files", T, true, {
                                        new SPPropertyString("Texture", T, "")}),
                                    new SPPropertyStruct("One file", T, true, {
                                        new SPPropertyString("Texture", T, "smoke2_a.tga"),
                                        new SPPropertyFloat("TotalAnimFrames", T, 1.0f, 2048.0f, 2.0f),
                                        new SPPropertyFloat("FirstAnimFrame", T, 0.0f, 2048.0f, 0.0f),
                                        new SPPropertyFloat("LastAnimFrame", T, 0.0f, 2048.0f, 1.0f)})}),
                                new SPPropertyEnum("LightingModel", T, 0, {{"None", 0}, {"Point (1 Color)", 1}, {"Point (2 Colors)", 2}}),
                                new SPPropertyColor("LightColor1", T, 0xFFFFFF),
                                new SPPropertyColor("LightColor2", T, 0xFF0000),
                                new SPPropertyFloat("OverLight1", T, 0.0f, 8.0f, 1.0f),
                                new SPPropertyFloat("LightRange", T, 0.0f, FLT_MAX, 1e+01f),
                                new SPPropertyTrack("LightIntensity", T,
                                    new SPPropertyStruct("Options", T, true, {
                                        new SPPropertyBool("Loop", T, false),
                                        new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                    new SPPropertyArray("Keys", T, 1, 128, 1,
                                        new SPPropertyStruct("Key", T, false, {
                                            new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                            new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                                new SPPropertyFloat("LightDuration", "Milyen hosszan vilagitsanak a particle-k", 0.0f, 1e+02f, 1.0f),
                                new SPPropertyBool("FixedLightSource", "A feny abban a pozicioban marad, ahol az elso frame-ben a particle forras volt.", false)}),
                            new SPPropertyStruct("Object", T, true, {
                                new SPPropertyString("Mesh file", T, "")}),
                            new SPPropertyStruct("Effect", T, true, {
                                new SPPropertyString("FX file", T, "effects/smoke_trail.fx")}),
                            new SPPropertyStruct("Trail", T, true, {
                                new SPPropertyFloat("valami", T, 0.0f, 1.0f, 0.5f)})}),
                        new SPPropertyStruct("Tracks", T, false, {
                            new SPPropertyTrack("Alpha", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                            new SPPropertyTrack("Size", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1e+02f, 0.6f)}))),
                            new SPPropertyFloat("Size_Rnd", T, 0.0f, 1e+02f, 0.0f),
                            new SPPropertyTrack("AdditionalSpeed", "Kulonbozo idopillanatokban a kezdo sebesseg hanyszorosat adja hozza az aktualis sebesseghez.",
                                new SPPropertyStruct("Options", nullptr, true, {
                                    new SPPropertyBool("Loop", nullptr, false),
                                    new SPPropertyFloat("Max. Y", nullptr, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", nullptr, 1, 128, 1,
                                    new SPPropertyStruct("Key", nullptr, false, {
                                        new SPPropertyFloat("X", nullptr, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1e+03f, 0.0f)})))}),
                        new SPPropertyStruct("Birth", T, false, {
                            new SPPropertyMulti("Style", "", 0, {
                                new SPPropertyStruct("Centralized", T, true, {}),
                                new SPPropertyStruct("Along the edge", T, true, {
                                    new SPPropertyInt("Quantity", "Hany db partice szulessen. 0 eseten annyi, ahany pont kijon a Sampling Rate-tol fuggoen", 0, 100000, 0)}),
                                new SPPropertyStruct("From Basement", T, true, {})}),
                            new SPPropertyFloat("BirthSpeed", T, 0.001f, FLT_MAX, 1e+01f),
                            new SPPropertyFloat("Duration", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("LifeTime", T, 0.01f, FLT_MAX, 1.0f),
                            new SPPropertyFloat("LifeTime_Rnd", T, 0.0f, FLT_MAX, 1.0f),
                            new SPPropertyBool("Sphere", "Gomb alapu legyen-e a keletkezes. Ha igen, akkor egy radius sugaru gombben keletkeznek majd a particle-k, egyebkent egy radius sugaru korben.", false),
                            new SPPropertyFloat("Radius", "A gomb/kor sugara, melyben a particle-k keletkezni fognak. Ha nulla, akkor a kov. 3 valtozo alapjan egy teglalap teruleten lesz a keletkezes, random eloszlassal.", 0.0f, FLT_MAX, 1.0f),
                            new SPPropertyFloat("RandomX", "Centralized Style es radius nulla eseten a teglatest X kiterjedese, melyben a particle-k keletkeznek, egyeb style-nal veletlenszeru particle pozicio elteres.", 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("RandomY", "Centralized Style es radius nulla eseten a teglatest Y kiterjedese, melyben a particle-k keletkeznek, egyeb style-nal veletlenszeru particle pozicio elteres.", 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("RandomZ", "Centralized Style es radius nulla eseten a teglatest Z kiterjedese, melyben a particle-k keletkeznek, egyeb style-nal veletlenszeru particle pozicio elteres.", 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("Sampling rate", "A mintavetelezes gyakorisaga 'Along the edge' es 'From basement' Birth Style-oknal, avagy milyen surun legyenek a particlek", 0.1f, 1e+01f, 1.0f),
                            new SPPropertyFloat("VSpeed", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SPPropertyFloat("VSpeed_Rnd", T, -FLT_MAX, FLT_MAX, 1.0f),
                            new SPPropertyFloat("HSpeed", T, -FLT_MAX, FLT_MAX, 0.0f),
                            new SPPropertyFloat("HSpeed_Rnd", T, -FLT_MAX, FLT_MAX, 0.0f),
                            new SPPropertyBool("FromTerrain", "Ha true, akkor a talaj alol indulnak a particle-k. Ha Collision-t is akarsz, akkor adjal meg egy kis altitude-t is (pl. 0.02)", false),
                            new SPPropertyBool("FromWater", "Ha true, akkor a viz alol indulnak a particle-k. Ha Collision-t is akarsz, akkor adjal meg egy kis altitude-t is (pl. 0.02)", false),
                            new SPPropertyFloat("Altitude", "Talaj feletti magassag (meterben), ha nem pont a talajnal akarunk keletkeztetni", -1e+01f, 1e+01f, 0.0f),
                            new SPPropertyEnum("CollisionType", "Mi tortenjen, ha a particle talajjal utkozik. None: nincs utkozes vizsgalat (atesik a talajon)  Slide: csuszik a talajon  Disappear: megszunik a particle, ha talajjal utkozik", 1, {{"None", 0}, {"Slide", 1}, {"Disappear", 2}, {"Jump", 3}}),
                            new SPPropertyFloat("CollisionSticking", "", 0.0f, 1.0f, 0.3f),
                            new SPPropertyFloat("GrowTime", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("GrowSpeed", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("BirthEnabledTime", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("BirthEnabledTimeRND", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("BirthDisabledTime", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("BirthDisabledTimeRND", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyBool("Birth in rain", T, true),
                            new SPPropertyMulti("Balanced birth", "Alacsonyabb FPS-eknel is megfeleloen szetszortan keletkeznek a particle-k. Pl. a langszoronal erdemes hasznalni. There is no: nincs aktivalva (ha csak lehet ezt erdemes hasznalni)  Direction: effekt pivot iranyba szoras", 0, {
                                new SPPropertyStruct("There is no", T, true, {}),
                                new SPPropertyStruct("Direction", T, true, {})})}),
                        new SPPropertyMulti("Move", "Shot: particle-k kilovese   Random: veletlenszeru mozgatas egy bizonyos koron belul (pl. szemetet fujja a szel)", 0, {
                            new SPPropertyStruct("Shot", T, true, {
                                new SPPropertyEnum("VariationType", T, 0, {{"Random", 0}, {"Animate", 1}}),
                                new SPPropertyFloat("Gravity", T, -FLT_MAX, FLT_MAX, 0.0f),
                                new SPPropertyFloat("AirResistance", "Elavult. Hasznald helyette az AdditionalSpeed-et.", 0.0f, 1.0f, 0.0f),
                                new SPPropertyFloat("AirResistance2", "Elavult. Hasznald helyette az AdditionalSpeed-et.", 0.0f, 1.0f, 1.0f),
                                new SPPropertyBool("Turbulence", "A turbulencia emulalas abbol all, hogy a mozgasirannyal ellentetes iranyban kicsapodnak a particle-k (a trail-ek is beallnak a kicsapodas iranyaba). A PivotDir legyen true, a Linked lehet true.", false),
                                new SPPropertyBool("NoWind", T, true),
                                new SPPropertyBool("Object Spin", "Object forgatas ki-be kapcsolasa. Kikapcsolasanak ertelme nullakra allitgatas helyett: sebesseg optimalizacio.", false),
                                new SPPropertyFloat("X Spin Minimum", "Az X tengely koruli perdulet minimuma. A min. es a max. kozotti veletlenszamnak megfelelo fokot fog elfordulni az objektum masodpercenkent.", -1e+04f, 1e+04f, 0.0f),
                                new SPPropertyFloat("X Spin Random", "Az X tengely koruli perdulet maximuma. A min. es a max. kozotti veletlenszamnak megfelelo fokot fog elfordulni az objektum masodpercenkent.", -1e+04f, 1e+04f, 0.0f),
                                new SPPropertyFloat("Y Spin Minimum", "Az Y tengely koruli perdulet minimuma. A min. es a max. kozotti veletlenszamnak megfelelo fokot fog elfordulni az objektum masodpercenkent.", -1e+04f, 1e+04f, 0.0f),
                                new SPPropertyFloat("Y Spin Random", "Az Y tengely koruli perdulet maximuma. A min. es a max. kozotti veletlenszamnak megfelelo fokot fog elfordulni az objektum masodpercenkent.", -1e+04f, 1e+04f, 0.0f),
                                new SPPropertyFloat("Z Spin Minimum", "Az Z tengely koruli perdulet minimuma. A min. es a max. kozotti veletlenszamnak megfelelo fokot fog elfordulni az objektum masodpercenkent.", -1e+04f, 1e+04f, 0.0f),
                                new SPPropertyFloat("Z Spin Random", "Az Z tengely koruli perdulet maximuma. A min. es a max. kozotti veletlenszamnak megfelelo fokot fog elfordulni az objektum masodpercenkent.", -1e+04f, 1e+04f, 0.0f)}),
                            new SPPropertyStruct("Waste", T, true, {
                                new SPPropertyEnum("VariationType", T, 0, {{"Random", 0}, {"Animate", 1}}),
                                new SPPropertyFloat("Gravity", T, -FLT_MAX, FLT_MAX, 0.0f),
                                new SPPropertyFloat("MinSpeed", "Minimalisan ilyen sebesseggel fogja fujni a szemetet a szel.", 0.0f, 1e+01f, 0.5f),
                                new SPPropertyFloat("MaxSpeed", "Maximalisan ilyen sebesseggel fogja fujni a szemetet a szel.", 0.1f, 1e+01f, 1.0f),
                                new SPPropertyFloat("MinWaitTime", "Max. mennyit varjon egy szemet ket szellokes kozott", 0.0f, 1e+02f, 5.0f),
                                new SPPropertyFloat("MaxWaitTime", "Min. mennyit varjon egy szemet ket szellokes kozott", 0.0f, 1e+02f, 2.0f)})}),
                        new SPPropertyStruct("General", T, false, {
                            new SPPropertyEnum("ManageType", T, 0, {{"0", 0}, {"1", 1}, {"2", 2}, {"3", 3}}),
                            new SPPropertyBool("Linked", T, false),
                            new SPPropertyBool("PivotDir", T, false),
                            new SPPropertyBool("TrailDirectionUpdate", "PivotDir=true eseten a PivotDir valtozasaval valtozzon-e az osszes trail iranya is egyben. Turbulance=false mellett hasznalando.", false),
                            new SPPropertyBool("Bullet Indicator", "Lovedeket jelkepez-e az effekt (pl. langszoros, nyomkoveto.) Ha ezt hasznaljuk, akkor ez legyen az egyetlen / legelso effekt az effektsetben!", false),
                            new SPPropertyFloat("Wait", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyFloat("Wait_Rnd", T, 0.0f, FLT_MAX, 0.0f),
                            new SPPropertyInt("Version", T, 0, 10000, 0),
                            new SPPropertyInt("ID for Debug", "Tetszoleges szam, ami alapjan fel lehet ismerni az effektet debbugolasnal.", 0, 1000, 0)})}),
                    new SPPropertyStruct("01_FLARE", T, true, {
                        new SPPropertyStruct("Draw", T, false, {
                            new SPPropertyString("Texture", T, "Glow_hq.tga"),
                            new SPPropertyInt("Variations", T, 1, 64, 1),
                            new SPPropertyColor("Color", "The color of the flare.", 0xFFFFFF),
                            new SPPropertyFloat("Alpha", T, 0.0f, 1.0f, 1.0f),
                            new SPPropertyFloat("Alpha_Exp", T, 0.01f, 1e+02f, 1.0f),
                            new SPPropertyFloat("Scale", T, 0.01f, 1e+02f, 1.0f),
                            new SPPropertyFloat("Scale_Exp", T, 0.01f, 1e+02f, 1.0f),
                            new SPPropertyBool("Directional", "Specifies if the glow is only visible from the direction of the effect.", true)})}),
                    new SPPropertyStruct("02_RAIN", T, true, {
                        new SPPropertyStruct("Birth", T, true, {
                            new SPPropertyFloat("Duration", T, 0.01f, FLT_MAX, 5e+01f),
                            new SPPropertyTrack("RainDropNum", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 4e+02f, 1e+02f)}))),
                            new SPPropertyFloat("VertSpeed", T, 1.0f, 4e+01f, 2e+01f),
                            new SPPropertyFloat("VertSpeed_Rnd", T, 0.0f, 2e+01f, 8.0f),
                            new SPPropertyString("Texture", T, "Esocsepp_a.tga"),
                            new SPPropertyInt("Variations", T, 1, 64, 1),
                            new SPPropertyColor("Color", T, 0xFFFFFF),
                            new SPPropertyFloat("Alpha", T, 0.0f, 1.0f, 1.0f)})}),
                    new SPPropertyStruct("03_SNOWFALL", T, true, {
                        new SPPropertyStruct("Birth", T, true, {
                            new SPPropertyFloat("Duration", T, 0.01f, FLT_MAX, 5e+01f),
                            new SPPropertyTrack("SnowFlakeNum", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 4e+02f, 1e+02f)}))),
                            new SPPropertyFloat("VertSpeed", T, 1.0f, 2e+01f, 3.0f),
                            new SPPropertyFloat("VertSpeed_Rnd", T, 0.0f, 2e+01f, 1.0f),
                            new SPPropertyString("Texture", T, "SnowFlakes_a.tga"),
                            new SPPropertyInt("Variations", T, 1, 64, 4),
                            new SPPropertyColor("Color", T, 0xFFFFFF),
                            new SPPropertyFloat("Alpha", T, 0.0f, 1.0f, 1.0f)})}),
                    new SPPropertyStruct("04_DECALEFFECT", T, true, {
                        new SPPropertyEnum("BlendType", T, 1, {{"Alpha", 0}, {"Add", 1}}),
                        new SPPropertyArray("Textures", "Textúrák :-)", 1, 8, 1,
                            new SPPropertyString("Texture", "Textúra", "shaderlight.tga")),
                        new SPPropertyBool("ForceBright", T, false),
                        new SPPropertyFloat("Duration", T, 0.0f, FLT_MAX, 1.0f),
                        new SPPropertyBool("RealTime", "Ha ez true, akkor pause-ban sem áll meg az effekt.", false),
                        new SPPropertyTrack("Alpha", T,
                            new SPPropertyStruct("Options", T, true, {
                                new SPPropertyBool("Loop", T, false),
                                new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                            new SPPropertyArray("Keys", T, 1, 128, 1,
                                new SPPropertyStruct("Key", T, false, {
                                    new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                    new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                        new SPPropertyTrack("Scale", T,
                            new SPPropertyStruct("Options", T, true, {
                                new SPPropertyBool("Loop", T, false),
                                new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                            new SPPropertyArray("Keys", T, 1, 128, 1,
                                new SPPropertyStruct("Key", T, false, {
                                    new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                    new SPPropertyFloat("Y", T, 0.01f, 1e+02f, 1.0f)}))),
                        new SPPropertyBool("Unstoppable", T, false),
                        new SPPropertyBool("RandomRotate", "A keletkezésnél random elforgatja a decal-eket.", false)}),
                    new SPPropertyStruct("05_SOUNDEFFECT", T, true, {
                        new SPPropertyStruct("Birth", T, true, {
                            new SPPropertyEnum("SoundGroup", "Specifies the type of the sound.", 0, {{"Ambient", 0}, {"Engine", 1}}),
                            new SPPropertyBool("Looping", "Specifies if the sound effect is looping.", true),
                            new SPPropertyString("SoundFile", T, "ambient/from swine test only/szel54.mp3"),
                            new SPPropertyString("SoundFile2", T, ""),
                            new SPPropertyString("SoundFile3", T, ""),
                            new SPPropertyBool("Positional", "Megadja, hogy a hangeffekt pozicionális-e (ha nem, akkor azonos hangerõvel szól az egész pályán)", false),
                            new SPPropertyFloat("Distance_Min", "Ha a megadott távolságon belül van a kamera, akkor a hangerõ maximális, távolodva egyre halkabb.", 0.01f, 1e+02f, 1e+01f),
                            new SPPropertyTrack("Volume", "A hang maximális hangereje (csak loopolt és nem-poziconális effekteknél).",
                                new SPPropertyStruct("Options", nullptr, true, {
                                    new SPPropertyBool("Loop", nullptr, false),
                                    new SPPropertyFloat("Max. Y", nullptr, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", nullptr, 1, 128, 1,
                                    new SPPropertyStruct("Key", nullptr, false, {
                                        new SPPropertyFloat("X", nullptr, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                            new SPPropertyFloat("Duration", "A hangeffekt idõtartama", 0.01f, FLT_MAX, 1.0f),
                            new SPPropertyInt("RNDFrequency", "Lejátszási frekvencia +/- %-os megváltoztatása (0%= nincs változás)", 0, 100, 0)})}),
                    new SPPropertyStruct("06_ATMOSPHERE", T, true, {
                        new SPPropertyStruct("Ambient Light", T, false, {
                            new SPPropertyBool("Active", T, false),
                            new SPPropertyFloat("Duration", T, 0.0f, FLT_MAX, 1.0f),
                            new SPPropertyColor("Color", T, 0xFFFFFF),
                            new SPPropertyTrack("Track", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1.0f, 0.0f)})))}),
                        new SPPropertyStruct("Sun Light", T, false, {
                            new SPPropertyBool("Active", T, false),
                            new SPPropertyColor("Color", T, 0xFFFFFF),
                            new SPPropertyTrack("Track", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1.0f, 0.0f)})))})}),
                    new SPPropertyStruct("07_LITE", T, true, {
                        new SPPropertyColor("Color", T, 0xFFFFFF),
                        new SPPropertyFloat("Duration", T, 0.01f, FLT_MAX, 1.0f),
                        new SPPropertyFloat("Range", T, 0.01f, FLT_MAX, 8.0f),
                        new SPPropertyFloat("Attenuation", T, 0.0f, FLT_MAX, 1.0f),
                        new SPPropertyTrack("Brightness", T,
                            new SPPropertyStruct("Options", T, true, {
                                new SPPropertyBool("Loop", T, false),
                                new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                            new SPPropertyArray("Keys", T, 1, 128, 1,
                                new SPPropertyStruct("Key", T, false, {
                                    new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                    new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                        new SPPropertyBool("Unstoppable", T, false),
                        new SPPropertyFloat("Altitude", "Ha 0, akkor az eredeti magassagot hasznalja, ha nem nulla, akkor a talaj fole helyezi megadott meterrel.", 0.0f, 2e+01f, 0.0f)}),
                    new SPPropertyStruct("08_TRAIL", T, true, {
                        new SPPropertyColor("Color", "A smoketrail szine.", 0xFFFFFF),
                        new SPPropertyString("Texture", "Textura file nev. Ezt a texturat fogja beismetelni a smoketrail-hez.", "effects/media/smoketrail_a.tga"),
                        new SPPropertyFloat("Strength", "Milyen erossen jelenjen meg a trail.", 0.0f, 1e+01f, 1.0f),
                        new SPPropertyFloat("FadeSpeed", "Milyen gyorsan fade-eljenek ki a mar kint levo reszek.", 0.001f, 1.0f, 0.01f),
                        new SPPropertyTrack("Alpha", "Az egyes helyek alpha-ja. Ha particlebol lett meghivva, akkor meg erre RASZORZODIK a hivo effekt alpha track-je",
                            new SPPropertyStruct("Options", nullptr, true, {
                                new SPPropertyBool("Loop", nullptr, false),
                                new SPPropertyFloat("Max. Y", nullptr, 0.1f, FLT_MAX, 1.0f)}),
                            new SPPropertyArray("Keys", nullptr, 1, 128, 1,
                                new SPPropertyStruct("Key", nullptr, false, {
                                    new SPPropertyFloat("X", nullptr, 0.0f, 1.0f, 0.0f),
                                    new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                        new SPPropertyTrack("Size", "Az egyes helyek merete-ja. Ha particlebol lett meghivva, akkor meg ehhez HOZZAADODIK a hivo effekt size track-je",
                            new SPPropertyStruct("Options", nullptr, true, {
                                new SPPropertyBool("Loop", nullptr, false),
                                new SPPropertyFloat("Max. Y", nullptr, 0.1f, FLT_MAX, 1.0f)}),
                            new SPPropertyArray("Keys", nullptr, 1, 128, 1,
                                new SPPropertyStruct("Key", nullptr, false, {
                                    new SPPropertyFloat("X", nullptr, 0.0f, 1.0f, 0.0f),
                                    new SPPropertyFloat("Y", T, 0.0f, 1e+01f, 1.0f)}))),
                        new SPPropertyFloat("Duration", "Az alpha es size track hossza. Figyelem! Az effekt nem a duration lejartaval, hanem 0-s alpha eseten tunik el!", 0.1f, 1e+01f, 1.0f),
                        new SPPropertyFloat("U_Scale", "Milyen szeles legyen a trail", 0.001f, 1.0f, 0.01f),
                        new SPPropertyFloat("V_Scale", "Hanyszor ismetelje be a texturat egy csempenyi tav alatt", 0.001f, 1e+01f, 1.0f),
                        new SPPropertyEnum("DrawType", "A rajzolas tipusa: Normal: normal, pixel-kihagyasos es alpha-s texturakhoz Add: addos texturakhoz.", 0, {{"Normal", 0}, {"Add", 1}})}),
                    new SPPropertyStruct("09_SHOCKWAVE", T, true, {}),
                    new SPPropertyStruct("10_CAMERASHAKE", T, true, {
                        new SPPropertyStruct("Birth", T, true, {
                            new SPPropertyBool("Positional", "Megadja, hogy a camera shake pozicionális-e (ha nem, akkor azonos erõvel hat az egész pályán)", false),
                            new SPPropertyFloat("Strength", "A rezgés kitérése méterben (poziconális effektnél 10m-es távolságban).", 0.01f, FLT_MAX, 1.0f),
                            new SPPropertyTrack("Amplitude", "A rezgés relatív kitérése",
                                new SPPropertyStruct("Options", nullptr, true, {
                                    new SPPropertyBool("Loop", nullptr, false),
                                    new SPPropertyFloat("Max. Y", nullptr, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", nullptr, 1, 128, 1,
                                    new SPPropertyStruct("Key", nullptr, false, {
                                        new SPPropertyFloat("X", nullptr, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                            new SPPropertyFloat("Duration", "Az effekt idõtartama", 0.01f, FLT_MAX, 1.0f)})}),
                    new SPPropertyStruct("11_SANDSTORM", T, true, {
                        new SPPropertyStruct("Birth", T, true, {
                            new SPPropertyFloat("Duration", T, 0.01f, FLT_MAX, 1.0f),
                            new SPPropertyFloat("Duration_Rnd", T, 0.0f, FLT_MAX, 2.0f),
                            new SPPropertyInt("ParticleNum", T, 0, 2000, 200),
                            new SPPropertyFloat("FloatingSpeed", T, -1e+02f, 1e+02f, 0.0f),
                            new SPPropertyFloat("FloatingSpeed_Rnd", T, -1e+02f, 1e+02f, 0.0f),
                            new SPPropertyFloat("RotationSpeed", T, -1e+03f, 1e+03f, 0.5f),
                            new SPPropertyFloat("RotationSpeed_Rnd", T, -1e+03f, 1e+03f, -1.0f),
                            new SPPropertyFloat("ParticleSize", T, 0.0f, 2e+01f, 5.0f),
                            new SPPropertyFloat("ParticleSize_Rnd", T, 0.0f, 2e+01f, 1e+01f),
                            new SPPropertyString("Texture", T, "sandstorm_a.tga"),
                            new SPPropertyColor("Color", T, 0xFFFFFF),
                            new SPPropertyTrack("Alpha", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1.0f, 0.2f)}))),
                            new SPPropertyFloat("Elevation", T, 0.0f, 1e+02f, 2.0f),
                            new SPPropertyInt("MoveDirection", T, 0, 360, 0),
                            new SPPropertyInt("MoveDirection_Rnd", T, 0, 360, 360)})})})}));
}

// Part of SPixie::SPixie 0x6941e0 (0x69a603..0x69c986).
SPProperty* BuildEfxSchema()
{
    return
        new SPPropertyStruct("EFX", T, false, {
            new SPPropertyMulti("EffectType", T, 0, {
                new SPPropertyStruct("00_PARTICLES", T, true, {
                    new SPPropertyMulti("Draw", T, 0, {
                        new SPPropertyStruct("Particles", T, true, {
                            new SPPropertyEnum("ParticleType", T, 0, {{"Normal", 0}, {"Billboard", 1}, {"Cloud", 2}, {"Trail", 3}}),
                            new SPPropertyEnum("BlendType", T, 0, {{"Alpha", 0}, {"Add", 1}}),
                            new SPPropertyColor("Color", T, 0xFFFFFF),
                            new SPPropertyBool("Random rotate", T, false),
                            new SPPropertyMulti("Texture Anim in", T, 1, {
                                new SPPropertyStruct("More files", T, true, {
                                    new SPPropertyString("Texture", T, "")}),
                                new SPPropertyStruct("One file", T, true, {
                                    new SPPropertyString("Texture", T, "smoke2_a.tga"),
                                    new SPPropertyFloat("TotalAnimFrames", T, 1.0f, 2048.0f, 2.0f),
                                    new SPPropertyFloat("FirstAnimFrame", T, 0.0f, 2048.0f, 0.0f),
                                    new SPPropertyFloat("LastAnimFrame", T, 0.0f, 2048.0f, 1.0f)})}),
                            new SPPropertyEnum("LightingModel", T, 0, {{"None", 0}, {"Point (1 Color)", 1}, {"Point (2 Colors)", 2}}),
                            new SPPropertyColor("LightColor1", T, 0xFFFFFF),
                            new SPPropertyColor("LightColor2", T, 0xFF0000),
                            new SPPropertyFloat("OverLight1", T, 0.0f, 8.0f, 1.0f),
                            new SPPropertyFloat("LightRange", T, 0.0f, FLT_MAX, 1e+01f),
                            new SPPropertyTrack("LightIntensity", T,
                                new SPPropertyStruct("Options", T, true, {
                                    new SPPropertyBool("Loop", T, false),
                                    new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                                new SPPropertyArray("Keys", T, 1, 128, 1,
                                    new SPPropertyStruct("Key", T, false, {
                                        new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                        new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)})))}),
                        new SPPropertyStruct("Object", T, true, {
                            new SPPropertyString("Mesh file", T, "")}),
                        new SPPropertyStruct("Effect", T, true, {
                            new SPPropertyString("FX file", T, "")})}),
                    new SPPropertyStruct("Tracks", T, false, {
                        new SPPropertyTrack("Alpha", T,
                            new SPPropertyStruct("Options", T, true, {
                                new SPPropertyBool("Loop", T, false),
                                new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                            new SPPropertyArray("Keys", T, 1, 128, 1,
                                new SPPropertyStruct("Key", T, false, {
                                    new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                    new SPPropertyFloat("Y", T, 0.0f, 1.0f, 1.0f)}))),
                        new SPPropertyTrack("Size", T,
                            new SPPropertyStruct("Options", T, true, {
                                new SPPropertyBool("Loop", T, false),
                                new SPPropertyFloat("Max. Y", T, 0.1f, FLT_MAX, 1.0f)}),
                            new SPPropertyArray("Keys", T, 1, 128, 1,
                                new SPPropertyStruct("Key", T, false, {
                                    new SPPropertyFloat("X", T, 0.0f, 1.0f, 0.0f),
                                    new SPPropertyFloat("Y", T, 0.0f, 1e+01f, 0.6f)}))),
                        new SPPropertyFloat("Size_Rnd", T, 0.0f, FLT_MAX, 0.0f)}),
                    new SPPropertyStruct("Birth", T, false, {
                        new SPPropertyFloat("BirthSpeed", T, 0.001f, FLT_MAX, 1e+01f),
                        new SPPropertyFloat("Duration", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("LifeTime", T, 0.01f, FLT_MAX, 1.0f),
                        new SPPropertyFloat("LifeTime_Rnd", T, 0.0f, FLT_MAX, 1.0f),
                        new SPPropertyBool("Sphere", T, false),
                        new SPPropertyFloat("Radius", T, 0.0f, FLT_MAX, 1.0f),
                        new SPPropertyFloat("RandomX", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("RandomY", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("RandomZ", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("VSpeed", T, -FLT_MAX, FLT_MAX, 1.0f),
                        new SPPropertyFloat("VSpeed_Rnd", T, -FLT_MAX, FLT_MAX, 1.0f),
                        new SPPropertyFloat("HSpeed", T, -FLT_MAX, FLT_MAX, 0.0f),
                        new SPPropertyFloat("HSpeed_Rnd", T, -FLT_MAX, FLT_MAX, 0.0f),
                        new SPPropertyBool("FromTerrain", "Ha true, akkor a talaj alol indulnak a particle-k. Ne hasznald egyutt utkozessel (collision type), mert keletkezes utan rogton utkozes lenne.", false),
                        new SPPropertyEnum("CollisionType", T, 1, {{"None", 0}, {"Slide", 1}}),
                        new SPPropertyFloat("GrowTime", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("GrowSpeed", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("BirthEnabledTime", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("BirthEnabledTimeRND", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("BirthDisabledTime", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyFloat("BirthDisabledTimeRND", T, 0.0f, FLT_MAX, 0.0f),
                        new SPPropertyMulti("Proba", T, 0, {
                            new SPPropertyStruct("d", T, true, {
                                new SPPropertyFloat("nev", T, 0.0f, 1.0f, 0.0f)}),
                            new SPPropertyStruct("e", T, true, {})})}),
                    new SPPropertyStruct("Move", T, false, {
                        new SPPropertyEnum("VariationType", T, 0, {{"Random", 0}, {"Animate", 1}}),
                        new SPPropertyFloat("Gravity", T, -FLT_MAX, FLT_MAX, 0.0f),
                        new SPPropertyFloat("AirResistance", T, 0.0f, 1.0f, 0.0f),
                        new SPPropertyFloat("AirResistance2", T, 0.0f, 1.0f, 0.0f),
                        new SPPropertyBool("NoWind", T, true)}),
                    new SPPropertyStruct("General", T, false, {
                        new SPPropertyEnum("ManageType", T, 0, {{"0", 0}, {"1", 1}, {"2", 2}, {"3", 3}}),
                        new SPPropertyBool("Linked", T, false),
                        new SPPropertyBool("PivotDir", T, false),
                        new SPPropertyInt("Version", T, 0, 10000, 0)})}),
                new SPPropertyStruct("01_FLARE", T, true, {
                    new SPPropertyStruct("Draw", T, false, {
                        new SPPropertyString("Texture", T, "Glow_hq.tga"),
                        new SPPropertyInt("Variations", T, 1, 64, 1),
                        new SPPropertyColor("Color", T, 0xFFFFFF),
                        new SPPropertyFloat("Alpha", T, 0.0f, 1.0f, 1.0f),
                        new SPPropertyFloat("Alpha_Exp", T, 0.01f, 1e+02f, 1.0f),
                        new SPPropertyFloat("Scale", T, 0.01f, 1e+02f, 1.0f),
                        new SPPropertyFloat("Scale_Exp", T, 0.01f, 1e+02f, 1.0f)})}),
                new SPPropertyStruct("02_RAIN", T, true, {
                    new SPPropertyStruct("Birth", T, false, {
                        new SPPropertyInt("RainDropNum", T, 1, 200, 20)}),
                    new SPPropertyStruct("Move", T, false, {
                        new SPPropertyFloat("VertSpeed", T, 1.0f, 4e+01f, 2e+01f),
                        new SPPropertyFloat("VertSpeed_Rnd", T, 0.0f, 2e+01f, 8.0f)}),
                    new SPPropertyStruct("Draw", T, false, {
                        new SPPropertyString("Texture", T, "Esocsepp_a.tga"),
                        new SPPropertyInt("Variations", T, 1, 64, 1),
                        new SPPropertyColor("Color", T, 0xFFFFFF),
                        new SPPropertyFloat("Alpha", T, 0.0f, 1.0f, 1.0f)})}),
                new SPPropertyStruct("03_SNOWFALL", T, false, {}),
                new SPPropertyStruct("04 (HIBAS)", T, false, {})})});
}

} // namespace pz
