// platform/statsandachievements.h
// Achievement and stat ID enums — shared between platform backends
// NOT from the original PDB — custom decompilation project header
// HDBEEFUP
// Enums reconstructed from: gameSplit/gog_platform.c
// Part of S.W.I.N.E. HD Remaster decompilation

#ifndef PLATFORM_STATSANDACHIEVEMENTS_H
#define PLATFORM_STATSANDACHIEVEMENTS_H

enum SAchievementID {
    ACH_COMPLETE_PIG_CAMPAIGN = 0,
    ACH_COMPLETE_RABBIT_CAMPAIGN,
    ACH_DESTROY_1000_PIG_UNITS,
    ACH_DESTROY_1000_RABBIT_UNITS,
    ACH_DESTROY_100_UNITS_WITH_MINES,
    ACH_REACH_MAX_RANK_WITH_UNIT,
    ACH_HAVE_UNIT_SURVIVE_ENTIRE_CAMPAIGN,
    ACH_1_UNIT_DESTROY_100_UNITS_IN_CAMPAIGN,
    ACH_DESTROY_DUG_IN_WITH_MORTAR,
    ACH_DESTROY_ELITE_WITH_STANDARD,
    ACH_COMPLETE_MISSION_WITH_ONLY_MORTAR,
    ACH_DESTROY_UNIT_IN_FOW,
    ACH_GET_HIT_BY_UNIT_IN_FOW,
    ACH_GET_UNIT_WITH_AIRDROP,
    ACH_DESTROY_3_UNITS_WITH_1_AIR_STRIKE,
    ACH_LOAD_3_TIMES_IN_A_MISSION,
    ACH_HAVE_3_EQUIPMENTS_FOR_1_UNIT,
    ACH_CAPTURE_ENEMY_TRAILER,
    ACH_WATCH_CREDITS,
    ACH_REACH_HUGE_XP_WITH_1_UNIT,
    ACH_REACH_HUGE_XP_WITH_3_UNIT,
    ACH_REACH_HUGE_XP_WITH_5_UNIT,
    ACH_REACH_HUGE_XP_WITH_10_UNIT,
    ACH_COUNT
};

enum SStatID {
    STAT_PIG_UNITS_DESTROYED = 0,
    STAT_RABBIT_UNITS_DESTROYED,
    STAT_UNITS_DESTROYED_WITH_MINES,
    STAT_MAX_UNITS_DESTROYED_BY_ONE_UNIT,
    STAT_COUNT
};

#endif // PLATFORM_STATSANDACHIEVEMENTS_H
